In [1]:
import numpy as np
n = [1, 2, 3]
n[0:2]

[1, 2]

In [2]:
n[-1]

3

In [3]:
a = np.array([1, 2, 3])
a[0:2]

array([1, 2])

In [4]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a[0:3, 1]

array([2, 4, 6])

In [5]:
a[-1]

array([5, 6])

In [6]:
a[:, 1: 2]

array([[2],
       [4],
       [6]])

In [11]:
for i in a.flat:
    print(i)

1
2
3
4
5
6


In [12]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [14]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [16]:
a = np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
res = np.hsplit(a, 3)
for i in res:
    print(i)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [20]:
res = np.vsplit(a, 2)
for i in res:
    print(i)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [21]:
a = np.arange(12).reshape(3, 4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [22]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])